# Generated by Django 5.0.3 on 2024-03-21 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Username", models.CharField(max_length=255)),
                ("Title", models.CharField(max_length=255)),
                ("Description", models.TextField(max_length=255)),
                ("Email", models.EmailField(max_length=254)),
                ("file", models.FileField(upload_to="")),
                ("Time", models.DateTimeField(auto_now=True)),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
    ]
