# Generated by Django 5.0.3 on 2024-03-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
